### ISSUE TITLE
textAnchor in README should be barAnchor

### ISSUE THREAD

**Issue by exside** [Remco75/chartist-plugin-barlabels#1]
Just noticed, that the readme instructions actually differ from the code, the readme says for the available options:

```
textAnchor: 'middle'
```

while the code is looking for barAnchor passed via options

```
style: 'text-anchor: ' + options.barAnchor
```

**Comment by Remco75** [comment]
Sorry, It has been a long time, and I don't work on this anymore, but I altered the readme (finally ;-)
