### ISSUE TITLE
Valid for pie charts?

### ISSUE THREAD

**Issue by Aldegunde** [Remco75/chartist-plugin-barlabels#2]
Hi, it is possible to use this plug in for pie charts?
If just possible for bar, where should I copy the plug in inside Chartist folder structure?

Thanks in advance.

**Comment by Remco75** [comment]
Hi @Aldegunde , for using chartist plugings see https://gionkunz.github.io/chartist-js/plugins.html#whats-a-plugin

It really doesn't matter where you place it, as long as you load it in your page ;-) And define it in the plugins array of your chart as described in the above mentioned page.

Will it work for pie's? just try, I didn't write it for that, and it has been some time, But i guess it will at least render something.
